site_name: Solana Handbook
site_url: https://ackee.xyz/solana/book
repo_url: https://github.com/Ackee-Blockchain/solana-handbook
repo_name: Ackee-Blockchain/solana-handbook
site_description: A comprehensive guide by Solana experts, covering core concepts, programming models and security.
site_author: Ackee Blockchain Security


edit_uri: ''

nav:
  - Solana Introduction:
      - chapter1/index.md
      - Introduction: chapter1/introduction.md
      - Blockchain: chapter1/blockchain.md
      - Transaction: chapter1/transaction.md
      - Infrastructure: chapter1/infrastructure.md
      - Security: chapter1/security.md
      - Slots, Epochs and Leaders: chapter1/slots-epochs-leaders.md
      - Smart Contract: chapter1/smart-contract.md
      - Ecosystem: chapter1/ecosystem.md
  - Core Concepts:
      - chapter2/index.md
      - Proof of History: chapter2/proof-of-history.md
      - Tower BFT: chapter2/tower-bft.md
      - Turbine: chapter2/turbine.md
      - Gulf Stream: chapter2/gulf-stream.md
      - Sealevel: chapter2/sealevel.md
      - Pipelining: chapter2/pipelining.md
      - Cloudbreak: chapter2/cloudbreak.md
      - Archivers: chapter2/archivers.md
  - Programming Model:
      - chapter3/index.md
      - Interacting with the Network: chapter3/interacting-with-the-network.md
      - Transaction Lifecycle: chapter3/transaction-lifecycle.md
      - Transaction Anatomy: chapter3/transaction-anatomy.md
      - Account Anatomy: chapter3/account-anatomy.md
      - Runtime Policy: chapter3/runtime-policy.md
      - Program Derived Address: chapter3/program-derived-address.md
      - Cross Program Invocation: chapter3/cross-program-invocation.md
  - Solana Program Library:
      - chapter4/index.md
      - Token Program: chapter4/token-program.md
      - Mint Account: chapter4/mint-account.md
      - Token Account: chapter4/token-account.md
      - Token-2022: chapter4/token-2022.md
      - Account Compression: chapter4/account-compression-program.md
  - Appendices:
    - appendices/index.md
    - Ecosystem:
      - Popular Projects: appendices/appendixA/popular-projects.md
    - NFTs:
      - Metaplex: appendices/appendixB/metaplex.md
      - Non-Fungible Tokens: appendices/appendixB/non-fungible-tokens.md
      - Token Metadata Program: appendices/appendixB/token-metadata-program.md
      - Storing Metadata Off-chain: appendices/appendixB/metadata-off-chain.md
      - Token Types: appendices/appendixB/token-types.md

# Beware this is strongly dependent on names of folders , example:
# images have to be stored within the docs/images folder
theme:
  # https://squidfunk.github.io/mkdocs-material/setup/
  name: material
  logo: "images/solana-logo-mark-1.png"
  favicon: "images/favicon.ico"
  custom_dir: overrides
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/?h=palette+sw#color-palette-toggle
  palette:
    - scheme: slate # dark mode scheme
      primary: black
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - scheme: default # light mode scheme
      primary: black
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
  features:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-expansion
    - navigation.expand
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#back-to-top-button
    - navigation.top
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages
    - navigation.indexes
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/?h=content+copy#code-copy-button
    - content.code.copy
    - navigation.tabs
    # may be used
    # - navigation.footer
  use_directory_urls: false

# https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/?h=social#social-links
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Ackee-Blockchain/solana-handbook
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Q3J5KUXuXK
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/AckeeBlockchain
  meta:
    description: "A comprehensive guide by experts on Solana, covering core concepts, programming models and security."
    keywords: "Solana, Solana Handbook, Solana Security, Solana Programming, Solana Development"
    author: "Ackee Blockchain Security"
    og:image: "images/solana-handbook-open-graph-image.png"  # Social media preview image

# https://www.mkdocs.org/user-guide/configuration/#plugins
plugins:
  - search
  - macros
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: false
  - social:
      cards_layout_options:
        background_color: "#000000"
        # background_image: images/solana-handbook-open-graph-image.png

# https://squidfunk.github.io/mkdocs-material/customization/?h=extra+css#additional-css
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  # https://squidfunk.github.io/mkdocs-material/reference/math/
  # used for fractions and math
  - pymdownx.arithmatex:
      generic: true
  # https://squidfunk.github.io/mkdocs-material/reference/data-tables/
  - tables
  # https://squidfunk.github.io/mkdocs-material/reference/math/
  # used for fractions and math
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
