site_name: Solana Handbook
site_url: https://ackeeblockchain.com/solana-handbook
repo_url: https://github.com/Ackee-Blockchain/solana-handbook
repo_name: Ackee-Blockchain/solana-handbook
site_description: For Experts by Experts
site_author: Ackee Blockchain

nav:
  - Getting started: index.md
  - Chapter 1 - Terminology:
      - Blockchain: handbook/chapter1/blockchain.md
      - Transaction: handbook/chapter1/transaction.md
      - Infrastructure: handbook/chapter1/infrastructure.md
      - Security: handbook/chapter1/security.md
      - Smart-Contract: handbook/chapter1/smart-contract.md
  - Chapter 2 - Solana Introduction:
      - Solana Introduction: handbook/chapter2/solana-introduction.md
      - Comparison to Ethereum: handbook/chapter2/comparison-to-ethereum.md
      - Rust Development: handbook/chapter2/rust-development.md
  - Chapter 3 - Core Concepts:
      - Core Concepts: handbook/chapter3/core-concepts.md
      - Proof of History: handbook/chapter3/proof-of-history.md
      - Tower BFT: handbook/chapter3/tower-bft.md
      - Turbine: handbook/chapter3/turbine.md
      - Gulf Stream: handbook/chapter3/gulf-stream.md
      - Sealevel: handbook/chapter3/sealevel.md
      - Pipelining: handbook/chapter3/pipelining.md
      - Cloudbreak: handbook/chapter3/cloudbreak.md
      - Archivers: handbook/chapter3/archivers.md
  - Chapter 4 - Programming Model:
      - Communication with Network: handbook/chapter4/communication-with-network.md
      - Overview: handbook/chapter4/overview.md
      - Transaction Key Elements: handbook/chapter4/transaction-key-elements.md
      - Transaction Anatomy: handbook/chapter4/transaction-anatomy.md
      - Account Anatomy: handbook/chapter4/account-anatomy.md
      - Runtime Policy: handbook/chapter4/runtime-policy.md
      - Calling between Programs: handbook/chapter4/calling-between-programs.md
  - Chapter 5 - Solana Program Library:
      - Solana Program Library: handbook/chapter5/solana-program-library.md
      - Token: handbook/chapter5/token-program.md
      - Associated Token: handbook/chapter5/associated-token-acc-program.md
      - Token 2022: handbook/chapter5/token-2022.md
      - Account Compression: handbook/chapter5/account-compression-program.md
  - Appendix A - Ecosystem:
      - Wallets: handbook/appendixA/wallets.md
      - Popular Projects: handbook/appendixA/popular-projects.md
      - Solana Mobile Phone: handbook/appendixA/solana-mobile-phone.md
  - Appendix B - NFTs:
      - NFTs: handbook/appendixB/nfts.md
      - What is Metaplex?: handbook/appendixB/what-is-metaplex.md
      - Token Metadata Program: handbook/appendixB/token-metadata-program.md
      - What has this got to do with NFTs?: handbook/appendixB/what-nfts.md
      - Is this all ? “No, Token Standard”: handbook/appendixB/token-standard.md
      - Candy Machine: handbook/appendixB/candy-machine.md
      - Compression: handbook/appendixB/compression.md
      - Storing Metadata Off-chain: handbook/appendixB/metadata-off-chain.md
      - Executable NFT: handbook/appendixB/executable-nft.md
  - Appendix C - Gaming:
      - Gaming: handbook/appendixC/index.md
  - About Authors: handbook/authors.md

# Beware this is strongly dependent on names of folders , example:
# images have to be stored within the docs/images folder
theme:
  # https://squidfunk.github.io/mkdocs-material/setup/
  name: material
  logo: "images/abch-logo.png"
  favicon: "images/favicon.ico"
  custom_dir: overrides
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/?h=palette+sw#color-palette-toggle
  palette:
    - scheme: default # light mode scheme
      primary: black
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate # dark mode scheme
      primary: black
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-expansion
    - navigation.expand
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#back-to-top-button
    - navigation.top
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages
    - navigation.indexes
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/?h=content+copy#code-copy-button
    - content.code.copy
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-sections
    - navigation.sections
    # may be used
    # - navigation.footer

# https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/?h=social#social-links
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Ackee-Blockchain/solana-handbook
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Q3J5KUXuXK
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/AckeeBlockchain

# https://www.mkdocs.org/user-guide/configuration/#plugins
plugins:
  - search
  - macros
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: false

# https://squidfunk.github.io/mkdocs-material/customization/?h=extra+css#additional-css
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  # https://squidfunk.github.io/mkdocs-material/reference/math/
  # used for fractions and math
  - pymdownx.arithmatex:
      generic: true
  # https://squidfunk.github.io/mkdocs-material/reference/data-tables/
  - tables
  # https://squidfunk.github.io/mkdocs-material/reference/math/
  # used for fractions and math
  - admonition

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
