name: Check if the MkDocs project is buildable

on:
  pull_request:

jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: ./.github/actions/setup-documentation/
      - name: Build documentation
        working-directory: .
        run: mkdocs build
